### ISSUE TITLE
the niceware backup phrase length can be reduced by half

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-client#11]
Right now it is 64 bytes. It could safely be reduced to 32 bytes if you save only the seed which is used to derive the signing keypair. See https://github.com/brave/sync/blob/staging/lib/crypto.js#L119-L121 for an example.

IMO this is a worthwhile change to make for usability's sake. Users would only have to write down 16 words to backup/recover the keypair instead of 32 words.

**Comment by diracdeltas** [comment]
depends on https://github.com/brave/sync/issues/160 which i am doing today

**Comment by diracdeltas** [comment]
shared crypto library is now available at https://www.npmjs.com/package/brave-crypto

**Comment by diracdeltas** [comment]
@mrose17 please don't merge before  a reviewer has finished reviewing, thanks.

**Comment by mrose17** [comment]
yes, @evq pointed out to me that you were a reviewer. i missed that. sorry!
