### ISSUE TITLE
Brave wallet recovery key #1 is unnecessary

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-client#12]
https://user-images.githubusercontent.com/3362943/31228726-6e5e714c-aa19-11e7-9b95-7fde0ab40e59.png

There seems to be no need for the UUID (Key 1 in the screenshot above) because we can use the Key 2 public key fingerprint as a wallet identifier. This would greatly improve usability for key backup and recovery.

**Comment by evq** [comment]
the browser side of this is fixed in https://github.com/brave/browser-laptop/pull/11231/commits/bb06b4bf09ee2c8526b9bbbf89c23b26037d0192
