### ISSUE TITLE
npm install fails if you don't have an ssh key

### ISSUE THREAD

**Issue by bridiver** [brave-intl/bat-client#24]
The root cause appears to be fixed in bitgojs
https://github.com/BitGo/BitGoJS/commit/6b2296fa1edfec87abef36a5d47c87acde167769
we should update when a new release is available

**Comment by evq** [comment]
updated to bitgo version `4.15.0` in https://github.com/brave-intl/bat-client/commit/5c784c1ad9a21f32e5339be45de6c1df84661057 which resolves this issue
