### ISSUE TITLE
set up travis

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-client#49]
this repo now has tests! it should run the tests and require passing tests for merge

**Comment by jasonrsadler** [comment]
Waiting for member status.

**Comment by diracdeltas** [comment]
@jasonrsadler i just approved the travis request - i noticed it was for travis-ci.com, which is OK, but we can use travis-ci.org in repos that are public

**Comment by jasonrsadler** [comment]
@diracdeltas Thanks. I had it in my head that it was a private repo for some reason.

**Comment by NejcZdovc** [comment]
closing this one as travis is added https://travis-ci.org/brave-intl/bat-client/builds/367432711?utm_source=github_status&utm_medium=notification
