### ISSUE TITLE
server should fallback to a valid URL

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-client#8]
the fallback should be 'https://ledger-staging.mercury.basicattentiontoken.org' instead of 'ledger-staging.mercury.basicattentiontoken.org' in https://github.com/brave-intl/bat-client/blob/2ed3fc79994a99fbfd7dadf2f3dae64293aca408/index.js#L36

**Comment by mrose17** [comment]
fixed in 0.9.16

good catch!
